spring.application.name=quiz

# ???? ??
#server.port = 8081
# Database ??
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/quiz_db
spring.datasource.username=spring
spring.datasource.password=a1234567890!

# JPA / Hibernate ??
# ???? SQL ?? ????
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true

# DDL ?? ?? ??
# create : ?? ?? ? ??? ??? ??(????)
# update : ??? ??? ??? ?? ??(????)
# validate : Entity? ???? ?? ??(???)
# none : ?? ?? ??.(??)
spring.jpa.hibernate.ddl-auto=validate

# MySQL ??(Dialect)
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# SQL ???? ??(?? ??)
logging.level.org.hibernate.type.descriptor.sql=trace

# SQL init ??(DB ??? ??? ??) - ?? true or false
spring.jpa.defer-datasource-initialization=false
# always : ?? ??, embedded : ??
spring.sql.init.mode=NEVER
